apiVersion : apps/v1
kind: Deployment
metadata:
  name: bapril27digital 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bapril27digital
  template:
    metadata:
      labels:
        app: bapril27digital 
    spec:
      containers:
        - name: bapril27digital 
          image: march30acr.azurecr.io/bapril27digital
          ports:
          - containerPort: 80